### ISSUE TITLE
Dialyzer warning

### ISSUE THREAD

**Issue by tomtaylor** [ajvondrak/remote_ip#20] opened 2020-04-01 11:50 UTC
When I run dialyzer on my project, I get the following warning which looks like it emanates from `remote_ip`:

```
lib/project/endpoint.ex:1:call_with_opaque
The call RemoteIp.call(__@1::#{'__struct__':='Elixir.Plug.Conn', 'adapter':={atom(),_}, 'assigns':=#{atom()=>_}, 'before_send':=[fun((_) -> any())], 'body_params':=#{'__struct__'=>'Elixir.Plug.Conn.Unfetched', 'aspect'=>atom(), binary()=>_}, 'cookies':=#{'__struct__'=>'Elixir.Plug.Conn.Unfetched', 'aspect'=>atom(), binary()=>_}, 'halted':=_, 'host':=binary(), 'method':=binary(), 'owner':=pid(), 'params':=#{'__struct__'=>'Elixir.Plug.Conn.Unfetched', 'aspect'=>atom(), binary()=>_}, 'path_info':=[binary()], 'path_params':=#{binary()=>binary() | [any()] | map()}, 'port':=char(), 'private':=#{atom()=>_}, 'query_params':=#{'__struct__'=>'Elixir.Plug.Conn.Unfetched', 'aspect'=>atom(), binary()=>binary() | [any()] | map()}, 'query_string':=binary(), 'remote_ip':={byte(),byte(),byte(),byte()} | {char(),char(),char(),char(),char(),char(),char(),char()}, 'req_cookies':=#{'__struct__'=>'Elixir.Plug.Conn.Unfetched', 'aspect'=>atom(), binary()=>binary()}, 'req_headers':=[{_,_}], 'request_path':=binary(), 'resp_body':='nil' | binary() | maybe_improper_list(binary() | maybe_improper_list(any(),binary() | []) | byte(),binary() | []), 'resp_cookies':=#{binary()=>map()}, 'resp_headers':=[{_,_}], 'scheme':='http' | 'https', 'script_name':=[binary()], 'secret_key_base':='nil' | binary(), 'state':='chunked' | 'file' | 'sent' | 'set' | 'set_chunked' | 'set_file' | 'unset', 'status':='nil' | non_neg_integer()},{'Elixir.MapSet':t(_),[any()]}) contains an opaque term in 2nd argument when terms of different types are expected in these positions}.
```

I haven't looked at fixing this yet, but I'll try and update when I get to it.

**Comment by tomtaylor** [comment] 2020-04-01 11:54
I think this is because `RemoteIp.call` should conform to the Plug behaviour, which expects its `opts` argument to be in the following format, according to [Plug's spec](https://hexdocs.pm/plug/Plug.html#c:call/2):

```
opts() ::
  binary()
  | tuple()
  | atom()
  | integer()
  | float()
  | [opts()]
  | %{optional(opts()) => opts()}
  | MapSet.t()
```

Passing a struct of `%RemoteIp.Config{}` breaks the spec. Is it possible to use a simple map for this?

**Comment by devstopfix** [comment] 2020-11-26 19:11
Relevant?  https://github.com/elixir-lang/elixir/issues/8463

**Comment by devstopfix** [comment] 2020-11-26 20:18
@tomtaylor I think I have a fix for this in 1749ea1

**Comment by devstopfix** [comment] 2020-11-26 20:55
And apologies for all the noise - I finally have a simple one file commit and PR!

**Comment by ajvondrak** [comment] 2021-01-24 01:36
> Passing a struct of `%RemoteIp.Config{}` breaks the spec. Is it possible to use a simple map for this?

@tomtaylor I can't reproduce your original warning, but the typespec accepts maps, per `%{optional(opts()) => opts()}`. Structs are just syntactially-sugared maps, so using `%RemoteIp.Config{}` should be fine.

Looking at the original output, it seems dialyzer was taking offense to the `{'Elixir.MapSet':t(_),[any()]}` in the 2nd position. So I think @devstopfix is probably onto something with the `MapSet` issue of elixir-lang/elixir#8463, which I _can_ reproduce locally.

If I'm reading the message right, it's still puzzling that a `MapSet` is appearing as the second argument to a `RemoteIp.call`. 🤔 But since I can't reproduce it, I'll defer to #25 as the way to close this issue.

**Closed as completed** 2021-01-24 01:37 UTC
